namespace SessionGuard.Core.Models;

public sealed record ServiceHealthSnapshot(
    string ServiceName,
    string DisplayName,
    string ProductVersion,
    string HostMode,
    string HealthState,
    string ProtocolVersion,
    string ExecutablePath,
    string BaseDirectory,
    string RepositoryRoot,
    string ConfigDirectory,
    string LogDirectory,
    string StateDirectory,
    string HealthFilePath,
    bool PipeServerListening,
    DateTimeOffset LastUpdatedAt,
    DateTimeOffset LastStartedAt,
    DateTimeOffset? LastStoppedAt = null,
    DateTimeOffset? PipeServerStartedAt = null,
    DateTimeOffset? LastSuccessfulScanAt = null,
    int? ScanIntervalSeconds = null,
    RestartStateCategory? LastScanState = null,
    RestartRiskLevel? LastScanRiskLevel = null,
    string? LastScanSummary = null,
    bool? LastGuardModeEnabled = null,
    bool? ApprovalWindowActive = null,
    DateTimeOffset? ApprovalWindowExpiresAt = null,
    int? ApprovalWindowMinutes = null,
    DateTimeOffset? ApprovalStateRecoveredAt = null,
    string? ApprovalStateSummary = null,
    string? LastErrorStage = null,
    DateTimeOffset? LastErrorAt = null,
    string? LastErrorMessage = null);
